{{- if .Values.config.create -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "radarcdmx-web.configSecretName" . }}
  labels:
    {{- include "radarcdmx-web.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{ .Values.config.fileName }}: |
    {{- .Values.config.content | nindent 4 }}
{{- end }}
