
ports:  
  grpc: 6011
  http: 8080

auth:
  jwt:
    key: << Key Here >>
  
db:
  - name: << Database Name Here>>
    host: << Database Host Here>>
    port: << Database Port Here>>
    user: << Database User Here>>
    pswd: << Database Password Here>>
    params: << Database Params Here>>
    driver: "<< Database Driver Here >>"

monitoring:
  enabled: false